function [data1, data2] = plaque_partition(data)
    arguments
        data (1, 1) MicrocountData
    end

    data1 = partition(data, true);
    data2 = partition(data, false);

end

function data1 = partition(data, in_plaque)
    arguments
        data (1, 1) MicrocountData
        in_plaque (1, 1) logical
    end

    if in_plaque
        idxs = data.overlap_pcs > 0;
    else
        idxs =  data.overlap_pcs == 0;
    end

    segmented = data.segmented;
    count = 1;
    for i = 1:data.nMicroglia 
        if ~idxs(i) 
            segmented(segmented == i) = 0;
        else
            segmented(segmented == i) = count;
            count = count + 1;
        end
    end
    
    data1 = MicrocountData( ...
        iba1            = data.iba1, ...
        cd68            = data.cd68, ...
        segmented       = segmented, ...
        iba1Mask        = data.iba1Mask, ...
        cell_areas      = data.cell_areas(idxs), ...
        cd68Mask        = data.cd68Mask, ...
        rotundities     = data.rotundities(idxs), ...
        detected        = data.detected & segmented > 0, ...
        branch_counts   = data.branch_counts(idxs), ...
        nActivated      = data.nActivated, ...
        nMicroglia      = numel(idxs), ...
        nPixels         = data.nPixels, ... 
        overlap_pcs     = data.overlap_pcs, ...
        poly_mask       = data.poly_mask & segmented > 0, ...
        skelly          = data.skelly & segmented > 0, ...
        soma_mask       = data.soma_mask & segmented > 0, ...
        soma_areas      = data.soma_areas(idxs), ...
        mm2_per_pixel   = data.mm2_per_pixel, ...
        um_per_pixel    = data.um_per_pixel, ...
        branch_lengths  = data.branch_lengths(idxs), ...
        dists_img       = data.dists_img, ...
        scholl_cross_matrix  = data.scholl_cross_matrix(idxs), ...
        region_mask     = data.region_mask, ...
        scholl_coeffs   = data.scholl_coeffs(idxs) ...
    );


end

